typography_spectrum: 0.9272492489056422
color:
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  brandStrength: 0.11453920211264919
  lightness: 0.91357176144008
  saturation: 0.25599484678385503
  rhythmicContrast: 0.6660924519047068
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5373343158796393
analytics:
  google: UA-26752917-1
  facebook: null
  twitter: null
author:
  name: Alan Snelson
  email: Alan@Wave2.org
  url: 'http://www.Wave2.org'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4112bc1-7bcc-4dd8-aef1-fa60ed323bd9.png
name: Wave2
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 75116da0-653b-4c57-a13b-2f465b36ffe8
    type: content
  - name: SoundCloud
    url: 'https://soundcloud.com/wave2'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/904dbce6-bfb3-44b6-b192-27218c595fbd.ico
title: Wave2
content: []
description: 'Unraveling the now, while working on the next...'
purpose: []
