name: Wave2
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41119
title: Wave2
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-26752917-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8320148852653801
  lightness: 0.22785438667051494
  saturation: 0.6297461641952395
  rhythmicContrast: 0.40275283716619015
purpose: []
