name: Wave2
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4112bc1-7bcc-4dd8-aef1-fa60ed323bd9.png
layout_spectrum: 0.13473811300379215
typography_spectrum: 0.2288550368402301
cta: {}
analytics:
  google: UA-26752917-1
opengraph: {}
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.13241048394766922
  lightness: 0.5265859738820334
  saturation: 0.2795024169676264
  rhythmicContrast: 0.0289051709510386
purpose: []
title: Wave2
description: 'Unraveling the now, while working on the next...'
author:
  name: Alan Snelson
  url: 'https://Wave2.org'
  email: Alan@Wave2.org
navigation:
  - name: About
    id: 75116da0-653b-4c57-a13b-2f465b36ffe8
    type: content
  - name: SoundCloud
    url: 'https://soundcloud.com/wave2'
    type: external
  - name: Twitter
    url: 'https://twitter.com/wave2'
    type: external
  - name: GitHub
    url: 'https://github.com/wave2'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/14552c8e-c23c-4d39-a437-68e7c7249ef8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/14552c8e-c23c-4d39-a437-68e7c7249ef8.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
