typography_spectrum: 0.007114713778719306
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.4759139106608927
  lightness: 0.5938515074085444
  saturation: 0.09412333811633289
  rhythmicContrast: 0.07866057776845992
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9881803600583225
analytics:
  google: UA-26752917-1
  facebook: null
  twitter: null
author:
  name: Alan Snelson
  email: Alan@Wave2.org
  url: 'http://www.Wave2.org'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4112bc1-7bcc-4dd8-aef1-fa60ed323bd9.png
name: Wave2
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 75116da0-653b-4c57-a13b-2f465b36ffe8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/904dbce6-bfb3-44b6-b192-27218c595fbd.ico
title: Wave2
description: 'Unraveling the now, while working on the next...'
purpose: []
