typography_spectrum: 0.11870562098920345
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.1925896394532174
  lightness: 0.2712814174592495
  saturation: 0.06464699073694646
  rhythmicContrast: 0.4658718293067068
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23800320830196142
analytics:
  google: UA-26752917-1
  facebook: null
  twitter: null
author:
  name: Alan Snelson
  email: Alan@Wave2.org
name: Wave2
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 935cb854-f242-4bd8-a038-574ff2fb3243
    url: 2016-02-28-935cb854-f242-4bd8-a038-574ff2fb3243.html
    name: About
    type: content
favicon: null
title: Wave2
purpose: []
