analytics:
  google: UA-26752917-1
color:
  brandColors:
    - '#C8C8C8'
    - '#2880A8'
    - '#909090'
    - '#3898C8'
    - '#000000'
  brandStrength: 0.298295
  lightness: 0.3125
  rhythmicContrast: 0.526278
  saturation: 0.372159
cta: {}
layout_spectrum: 1
name: Wave2
opengraph: {}
purpose: []
typography_spectrum: 0.49918
